### ISSUE TITLE
symbolic link not work

### ISSUE THREAD

**Issue by daolou** [mperezi/build-alfred-workflow#1]
First, use symbolic link some dir, such as `ln -s ./node_modules/alfy@1.0.0/node_modules/alfy ./node_modules/alfy`,

Second, build it and then download `.alfredworkflow`, and there noexist above symbolic link.

**Comment by mikybars** [comment]
You're right. I was missing the correct flag to the zip command. Make sure to try the action now with the corresponding commit id 557434a545657b1b5e7a7ed010de62ead21578cb and let me know if it works for you. Then I'll release a bugfix.

**Comment by mikybars** [comment]
There it is: https://github.com/mperezi/build-alfred-workflow/releases/tag/v1.0.1
